// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DisconnectRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *DisconnectRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type DisconnectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Revoke application access
	Status *string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DisconnectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DisconnectResponse) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *DisconnectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DisconnectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
