// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"testsdkcreation/pkg/models/shared"
)

type GetTeslaVoltageRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *GetTeslaVoltageRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type GetTeslaVoltageResponse struct {
	// returns the voltage of the charger measured by the vehicle.
	ChargeVoltage *shared.ChargeVoltage
	ContentType   string
	StatusCode    int
	RawResponse   *http.Response
}

func (o *GetTeslaVoltageResponse) GetChargeVoltage() *shared.ChargeVoltage {
	if o == nil {
		return nil
	}
	return o.ChargeVoltage
}

func (o *GetTeslaVoltageResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTeslaVoltageResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTeslaVoltageResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
