// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"testsdkcreation/pkg/models/shared"
)

type SetTeslaAmmeterRequest struct {
	VehicleID     string                `pathParam:"style=simple,explode=false,name=vehicle_id"`
	ChargeAmmeter *shared.ChargeAmmeter `request:"mediaType=application/json"`
}

type SetTeslaAmmeterResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// returns the amperage of the charger measured by the vehicle.
	SuccessResponse *shared.SuccessResponse
}
